/**
 * Production seed data — sourced from food.md (Level 2) and training.md.
 * @see src/constants/meals.ts for in-app mirror
 */

/** EU standard macros per 100 g (food.md ingredients table). */
const INGREDIENTS = [
  { id: 'chicken_breast', name: 'Chicken Breast', protein_per_100g: 23, fat_per_100g: 2, carbs_per_100g: 0, calories_per_100g: 110 },
  { id: 'rice_dry', name: 'Rice (dry)', protein_per_100g: 7, fat_per_100g: 1, carbs_per_100g: 78, calories_per_100g: 350 },
  { id: 'oats', name: 'Oats', protein_per_100g: 13, fat_per_100g: 7, carbs_per_100g: 60, calories_per_100g: 370 },
  { id: 'eggs', name: 'Eggs', protein_per_100g: 13, fat_per_100g: 11, carbs_per_100g: 1, calories_per_100g: 155 },
  { id: 'greek_yogurt', name: 'Greek Yogurt 2%', protein_per_100g: 10, fat_per_100g: 2, carbs_per_100g: 4, calories_per_100g: 70 },
  { id: 'olive_oil', name: 'Olive Oil', protein_per_100g: 0, fat_per_100g: 100, carbs_per_100g: 0, calories_per_100g: 900 },
  { id: 'salmon', name: 'Salmon', protein_per_100g: 20, fat_per_100g: 13, carbs_per_100g: 0, calories_per_100g: 208 },
  { id: 'banana', name: 'Banana', protein_per_100g: 1, fat_per_100g: 0, carbs_per_100g: 23, calories_per_100g: 96 },
  { id: 'whole_grain_bread', name: 'Whole Grain Bread', protein_per_100g: 9, fat_per_100g: 3, carbs_per_100g: 45, calories_per_100g: 240 },
  { id: 'berries', name: 'Mixed Berries', protein_per_100g: 1, fat_per_100g: 0.5, carbs_per_100g: 12, calories_per_100g: 57 },
  { id: 'vegetables', name: 'Mixed Vegetables', protein_per_100g: 2, fat_per_100g: 0.3, carbs_per_100g: 7, calories_per_100g: 35 },
  { id: 'whey', name: 'Whey Protein', protein_per_100g: 80, fat_per_100g: 5, carbs_per_100g: 8, calories_per_100g: 400 },
  { id: 'milk', name: 'Milk 2%', protein_per_100g: 3.4, fat_per_100g: 2, carbs_per_100g: 5, calories_per_100g: 50 },
  { id: 'pasta', name: 'Pasta (dry)', protein_per_100g: 13, fat_per_100g: 1.5, carbs_per_100g: 75, calories_per_100g: 370 },
  { id: 'tomato_sauce', name: 'Tomato Sauce', protein_per_100g: 1.5, fat_per_100g: 0.2, carbs_per_100g: 8, calories_per_100g: 40 },
  { id: 'teriyaki_sauce', name: 'Teriyaki Sauce', protein_per_100g: 5, fat_per_100g: 0, carbs_per_100g: 18, calories_per_100g: 89 },
  { id: 'quinoa', name: 'Quinoa (dry)', protein_per_100g: 14, fat_per_100g: 6, carbs_per_100g: 64, calories_per_100g: 368 },
  { id: 'turkey', name: 'Turkey Breast', protein_per_100g: 24, fat_per_100g: 1, carbs_per_100g: 0, calories_per_100g: 111 },
];

const MEALS = [
  {
    meal_id: 'protein_oat_bowl',
    name: 'Protein Oat Bowl',
    category: 'breakfast',
    cuisine: 'european',
    tier: 'mid',
    calories: 470,
    protein: 23,
    fat: 8,
    carbs: 70,
    goal_tags: ['fat_loss', 'maintenance', 'bulk'],
    prep_time: 10,
    swap_ids: ['yogurt_power_bowl', 'egg_breakfast_plate'],
    ingredients: [
      { id: 'oats', grams: 80 },
      { id: 'greek_yogurt', grams: 150 },
      { id: 'banana', grams: 100 },
    ],
  },
  {
    meal_id: 'chicken_rice_bowl',
    name: 'Chicken Rice Bowl',
    category: 'lunch',
    cuisine: 'european',
    tier: 'mid',
    calories: 560,
    protein: 41,
    fat: 14,
    carbs: 62,
    goal_tags: ['fat_loss', 'maintenance', 'bulk'],
    prep_time: 25,
    swap_ids: ['salmon_rice_bowl', 'turkey_quinoa_bowl', 'chicken_teriyaki_bowl'],
    ingredients: [
      { id: 'chicken_breast', grams: 150 },
      { id: 'rice_dry', grams: 80 },
      { id: 'olive_oil', grams: 10 },
    ],
  },
  {
    meal_id: 'salmon_rice_plate',
    name: 'Salmon Rice Plate',
    category: 'dinner',
    cuisine: 'european',
    tier: 'premium',
    calories: 580,
    protein: 35,
    fat: 20,
    carbs: 55,
    goal_tags: ['fat_loss', 'maintenance', 'bulk'],
    prep_time: 28,
    swap_ids: ['salmon_veg_plate', 'chicken_rice_bowl'],
    ingredients: [
      { id: 'salmon', grams: 140 },
      { id: 'rice_dry', grams: 70 },
      { id: 'vegetables', grams: 150 },
    ],
  },
  {
    meal_id: 'yogurt_snack_bowl',
    name: 'Yogurt Snack Bowl',
    category: 'snack',
    cuisine: 'european',
    tier: 'cheap',
    calories: 350,
    protein: 25,
    fat: 6,
    carbs: 45,
    goal_tags: ['fat_loss', 'maintenance'],
    prep_time: 5,
    swap_ids: ['protein_shake', 'yogurt_power_bowl'],
    ingredients: [
      { id: 'greek_yogurt', grams: 250 },
      { id: 'banana', grams: 100 },
      { id: 'oats', grams: 30 },
    ],
  },
  {
    meal_id: 'yogurt_power_bowl',
    name: 'Yogurt Power Bowl',
    category: 'breakfast',
    cuisine: 'european',
    tier: 'mid',
    calories: 390,
    protein: 30,
    fat: 7,
    carbs: 45,
    goal_tags: ['fat_loss', 'maintenance'],
    prep_time: 5,
    swap_ids: ['protein_oat_bowl', 'yogurt_snack_bowl'],
    ingredients: [
      { id: 'greek_yogurt', grams: 250 },
      { id: 'oats', grams: 40 },
      { id: 'berries', grams: 100 },
    ],
  },
  {
    meal_id: 'salmon_rice_bowl',
    name: 'Salmon Rice Bowl',
    category: 'lunch',
    cuisine: 'european',
    tier: 'premium',
    calories: 580,
    protein: 35,
    fat: 20,
    carbs: 55,
    goal_tags: ['maintenance', 'bulk'],
    prep_time: 30,
    swap_ids: ['chicken_rice_bowl', 'salmon_veg_plate'],
    ingredients: [
      { id: 'salmon', grams: 140 },
      { id: 'rice_dry', grams: 70 },
      { id: 'vegetables', grams: 150 },
    ],
  },
  {
    meal_id: 'salmon_veg_plate',
    name: 'Salmon Veg Plate',
    category: 'dinner',
    cuisine: 'european',
    tier: 'premium',
    calories: 520,
    protein: 34,
    fat: 25,
    carbs: 20,
    goal_tags: ['fat_loss', 'maintenance'],
    prep_time: 25,
    swap_ids: ['chicken_rice_bowl', 'chicken_veg_bowl'],
    ingredients: [
      { id: 'salmon', grams: 140 },
      { id: 'vegetables', grams: 200 },
      { id: 'olive_oil', grams: 10 },
    ],
  },
  {
    meal_id: 'chicken_veg_bowl',
    name: 'Chicken Veg Bowl',
    category: 'dinner',
    cuisine: 'european',
    tier: 'mid',
    calories: 500,
    protein: 42,
    fat: 10,
    carbs: 45,
    goal_tags: ['fat_loss', 'maintenance'],
    prep_time: 25,
    swap_ids: ['salmon_veg_plate', 'chicken_rice_bowl'],
    ingredients: [
      { id: 'chicken_breast', grams: 160 },
      { id: 'vegetables', grams: 200 },
      { id: 'rice_dry', grams: 50 },
    ],
  },
  {
    meal_id: 'protein_shake',
    name: 'Protein Shake',
    category: 'snack',
    cuisine: 'fitness',
    tier: 'cheap',
    calories: 220,
    protein: 25,
    fat: 5,
    carbs: 15,
    goal_tags: ['fat_loss', 'maintenance', 'bulk'],
    prep_time: 2,
    swap_ids: ['yogurt_snack_bowl'],
    ingredients: [
      { id: 'whey', grams: 30 },
      { id: 'milk', grams: 250 },
    ],
  },
  {
    meal_id: 'italian_chicken_pasta',
    name: 'Chicken Fit Pasta',
    category: 'lunch',
    cuisine: 'italian',
    tier: 'mid',
    calories: 640,
    protein: 45,
    fat: 12,
    carbs: 85,
    goal_tags: ['maintenance', 'bulk'],
    prep_time: 20,
    swap_ids: ['chicken_rice_bowl', 'chicken_teriyaki_bowl'],
    ingredients: [
      { id: 'pasta', grams: 90 },
      { id: 'chicken_breast', grams: 150 },
      { id: 'tomato_sauce', grams: 120 },
    ],
  },
  {
    meal_id: 'chicken_teriyaki_bowl',
    name: 'Chicken Teriyaki Bowl',
    category: 'lunch',
    cuisine: 'asian',
    tier: 'mid',
    calories: 590,
    protein: 42,
    fat: 10,
    carbs: 75,
    goal_tags: ['maintenance', 'bulk'],
    prep_time: 22,
    swap_ids: ['chicken_rice_bowl', 'italian_chicken_pasta'],
    ingredients: [
      { id: 'chicken_breast', grams: 150 },
      { id: 'rice_dry', grams: 80 },
      { id: 'teriyaki_sauce', grams: 30 },
    ],
  },
  {
    meal_id: 'turkey_quinoa_bowl',
    name: 'Turkey Quinoa Bowl',
    category: 'lunch',
    cuisine: 'european',
    tier: 'mid',
    calories: 590,
    protein: 42,
    fat: 15,
    carbs: 58,
    goal_tags: ['fat_loss', 'maintenance'],
    prep_time: 28,
    swap_ids: ['chicken_rice_bowl', 'salmon_rice_bowl'],
    ingredients: [
      { id: 'turkey', grams: 150 },
      { id: 'quinoa', grams: 80 },
      { id: 'olive_oil', grams: 10 },
    ],
  },
  {
    meal_id: 'egg_breakfast_plate',
    name: 'Egg Breakfast Plate',
    category: 'breakfast',
    cuisine: 'european',
    tier: 'cheap',
    calories: 480,
    protein: 28,
    fat: 22,
    carbs: 36,
    goal_tags: ['maintenance', 'bulk'],
    prep_time: 12,
    swap_ids: ['protein_oat_bowl', 'yogurt_power_bowl'],
    ingredients: [
      { id: 'eggs', grams: 180 },
      { id: 'whole_grain_bread', grams: 80 },
    ],
  },
];

const WORKOUT_PLANS = [
  {
    id: 'fat_loss_4_weeks',
    name: 'Fat Loss 4 Weeks',
    goal: 'fat_loss',
    duration_weeks: 4,
    level: 'beginner',
    days_per_week: 4,
    description:
      'Four-week conditioning split with full-body strength, cardio, and recovery slots for sustainable fat loss.',
    slots: [
      {
        day_index: 0,
        day_label: 'Mon',
        split_name: 'Full Body Burn A',
        is_rest: false,
        sort_order: 0,
        exercises: [
          { exercise_name: 'Goblet Squat', sets: 3, reps_min: 12, reps_max: 15, rest_seconds: 60, sort_order: 0 },
          { exercise_name: 'Dumbbell Bench Press', sets: 3, reps_min: 12, reps_max: 15, rest_seconds: 60, sort_order: 1 },
          { exercise_name: 'Lat Pulldown', sets: 3, reps_min: 12, reps_max: 15, rest_seconds: 60, sort_order: 2 },
          { exercise_name: 'Plank', sets: 3, reps_min: 30, reps_max: 45, rest_seconds: 45, sort_order: 3 },
        ],
      },
      {
        day_index: 1,
        day_label: 'Tue',
        split_name: 'Cardio + Core',
        is_rest: false,
        sort_order: 1,
        exercises: [
          { exercise_name: 'Incline Walk', sets: 1, reps_min: 25, reps_max: 30, rest_seconds: 0, sort_order: 0 },
          { exercise_name: 'Mountain Climbers', sets: 3, reps_min: 20, reps_max: 30, rest_seconds: 45, sort_order: 1 },
          { exercise_name: 'Bicycle Crunch', sets: 3, reps_min: 15, reps_max: 20, rest_seconds: 45, sort_order: 2 },
        ],
      },
      {
        day_index: 2,
        day_label: 'Wed',
        split_name: 'Rest',
        is_rest: true,
        sort_order: 2,
        exercises: [],
      },
      {
        day_index: 3,
        day_label: 'Thu',
        split_name: 'Full Body Burn B',
        is_rest: false,
        sort_order: 3,
        exercises: [
          { exercise_name: 'Romanian Deadlift', sets: 3, reps_min: 10, reps_max: 12, rest_seconds: 75, sort_order: 0 },
          { exercise_name: 'Overhead Press', sets: 3, reps_min: 10, reps_max: 12, rest_seconds: 75, sort_order: 1 },
          { exercise_name: 'Seated Cable Row', sets: 3, reps_min: 12, reps_max: 15, rest_seconds: 60, sort_order: 2 },
          { exercise_name: 'Walking Lunges', sets: 3, reps_min: 10, reps_max: 12, rest_seconds: 60, sort_order: 3 },
        ],
      },
      {
        day_index: 4,
        day_label: 'Fri',
        split_name: 'HIIT Circuit',
        is_rest: false,
        sort_order: 4,
        exercises: [
          { exercise_name: 'Kettlebell Swing', sets: 4, reps_min: 15, reps_max: 20, rest_seconds: 45, sort_order: 0 },
          { exercise_name: 'Push-ups', sets: 4, reps_min: 10, reps_max: 15, rest_seconds: 45, sort_order: 1 },
          { exercise_name: 'Row Erg', sets: 4, reps_min: 250, reps_max: 300, rest_seconds: 60, sort_order: 2 },
        ],
      },
      {
        day_index: 5,
        day_label: 'Sat',
        split_name: 'Active Recovery',
        is_rest: false,
        sort_order: 5,
        exercises: [
          { exercise_name: 'Light Walk', sets: 1, reps_min: 30, reps_max: 40, rest_seconds: 0, sort_order: 0 },
          { exercise_name: 'Mobility Flow', sets: 1, reps_min: 15, reps_max: 20, rest_seconds: 0, sort_order: 1 },
        ],
      },
      {
        day_index: 6,
        day_label: 'Sun',
        split_name: 'Rest',
        is_rest: true,
        sort_order: 6,
        exercises: [],
      },
    ],
  },
  {
    id: 'mass_gain_8_weeks',
    name: 'Mass Gain 8 Weeks',
    goal: 'mass_gain',
    duration_weeks: 8,
    level: 'intermediate',
    days_per_week: 5,
    description:
      'Eight-week hypertrophy block with progressive push, pull, and legs volume for lean mass gain.',
    slots: [
      {
        day_index: 0,
        day_label: 'Mon',
        split_name: 'Push Hypertrophy',
        is_rest: false,
        sort_order: 0,
        exercises: [
          { exercise_name: 'Barbell Bench Press', sets: 4, reps_min: 6, reps_max: 10, rest_seconds: 120, sort_order: 0 },
          { exercise_name: 'Incline Dumbbell Press', sets: 4, reps_min: 8, reps_max: 12, rest_seconds: 90, sort_order: 1 },
          { exercise_name: 'Overhead Press', sets: 3, reps_min: 8, reps_max: 10, rest_seconds: 90, sort_order: 2 },
          { exercise_name: 'Lateral Raise', sets: 4, reps_min: 12, reps_max: 15, rest_seconds: 60, sort_order: 3 },
          { exercise_name: 'Triceps Pushdown', sets: 3, reps_min: 10, reps_max: 15, rest_seconds: 60, sort_order: 4 },
        ],
      },
      {
        day_index: 1,
        day_label: 'Tue',
        split_name: 'Pull Hypertrophy',
        is_rest: false,
        sort_order: 1,
        exercises: [
          { exercise_name: 'Barbell Row', sets: 4, reps_min: 6, reps_max: 10, rest_seconds: 120, sort_order: 0 },
          { exercise_name: 'Lat Pulldown', sets: 4, reps_min: 8, reps_max: 12, rest_seconds: 90, sort_order: 1 },
          { exercise_name: 'Seated Cable Row', sets: 3, reps_min: 10, reps_max: 12, rest_seconds: 90, sort_order: 2 },
          { exercise_name: 'Face Pull', sets: 3, reps_min: 15, reps_max: 20, rest_seconds: 60, sort_order: 3 },
          { exercise_name: 'Barbell Curl', sets: 3, reps_min: 8, reps_max: 12, rest_seconds: 60, sort_order: 4 },
        ],
      },
      {
        day_index: 2,
        day_label: 'Wed',
        split_name: 'Legs Hypertrophy',
        is_rest: false,
        sort_order: 2,
        exercises: [
          { exercise_name: 'Barbell Squat', sets: 4, reps_min: 6, reps_max: 10, rest_seconds: 120, sort_order: 0 },
          { exercise_name: 'Romanian Deadlift', sets: 4, reps_min: 8, reps_max: 10, rest_seconds: 120, sort_order: 1 },
          { exercise_name: 'Leg Press', sets: 3, reps_min: 10, reps_max: 12, rest_seconds: 90, sort_order: 2 },
          { exercise_name: 'Leg Curl', sets: 3, reps_min: 12, reps_max: 15, rest_seconds: 60, sort_order: 3 },
          { exercise_name: 'Standing Calf Raise', sets: 4, reps_min: 12, reps_max: 15, rest_seconds: 60, sort_order: 4 },
        ],
      },
      {
        day_index: 3,
        day_label: 'Thu',
        split_name: 'Push Volume',
        is_rest: false,
        sort_order: 3,
        exercises: [
          { exercise_name: 'Dumbbell Bench Press', sets: 4, reps_min: 8, reps_max: 12, rest_seconds: 90, sort_order: 0 },
          { exercise_name: 'Cable Flyes', sets: 3, reps_min: 12, reps_max: 15, rest_seconds: 60, sort_order: 1 },
          { exercise_name: 'Arnold Press', sets: 3, reps_min: 10, reps_max: 12, rest_seconds: 90, sort_order: 2 },
          { exercise_name: 'Parallel Bar Dips', sets: 3, reps_min: 8, reps_max: 12, rest_seconds: 90, sort_order: 3 },
        ],
      },
      {
        day_index: 4,
        day_label: 'Fri',
        split_name: 'Pull + Legs',
        is_rest: false,
        sort_order: 4,
        exercises: [
          { exercise_name: 'Pull-ups', sets: 4, reps_min: 6, reps_max: 10, rest_seconds: 120, sort_order: 0 },
          { exercise_name: 'Single-Arm Dumbbell Row', sets: 3, reps_min: 10, reps_max: 12, rest_seconds: 90, sort_order: 1 },
          { exercise_name: 'Hack Squat', sets: 3, reps_min: 8, reps_max: 12, rest_seconds: 120, sort_order: 2 },
          { exercise_name: 'Hammer Curl', sets: 3, reps_min: 10, reps_max: 12, rest_seconds: 60, sort_order: 3 },
        ],
      },
      {
        day_index: 5,
        day_label: 'Sat',
        split_name: 'Rest',
        is_rest: true,
        sort_order: 5,
        exercises: [],
      },
      {
        day_index: 6,
        day_label: 'Sun',
        split_name: 'Rest',
        is_rest: true,
        sort_order: 6,
        exercises: [],
      },
    ],
  },
  {
    id: 'ppl_beginner',
    name: 'Push / Pull / Legs Beginner',
    goal: 'strength',
    duration_weeks: 12,
    level: 'beginner',
    days_per_week: 3,
    description:
      'Classic beginner push, pull, and legs template with foundational compound lifts and controlled volume.',
    slots: [
      {
        day_index: 0,
        day_label: 'Mon',
        split_name: 'Push',
        is_rest: false,
        sort_order: 0,
        exercises: [
          { exercise_name: 'Barbell Bench Press', sets: 4, reps_min: 8, reps_max: 10, rest_seconds: 90, sort_order: 0 },
          { exercise_name: 'Incline Dumbbell Press', sets: 3, reps_min: 10, reps_max: 12, rest_seconds: 90, sort_order: 1 },
          { exercise_name: 'Cable Flyes', sets: 3, reps_min: 12, reps_max: 15, rest_seconds: 60, sort_order: 2 },
          { exercise_name: 'Parallel Bar Dips', sets: 3, reps_min: 10, reps_max: 12, rest_seconds: 90, sort_order: 3 },
          { exercise_name: 'Overhead Press', sets: 3, reps_min: 8, reps_max: 10, rest_seconds: 90, sort_order: 4 },
          { exercise_name: 'Triceps Pushdown', sets: 3, reps_min: 12, reps_max: 15, rest_seconds: 60, sort_order: 5 },
        ],
      },
      {
        day_index: 1,
        day_label: 'Tue',
        split_name: 'Rest',
        is_rest: true,
        sort_order: 1,
        exercises: [],
      },
      {
        day_index: 2,
        day_label: 'Wed',
        split_name: 'Pull',
        is_rest: false,
        sort_order: 2,
        exercises: [
          { exercise_name: 'Lat Pulldown', sets: 4, reps_min: 8, reps_max: 10, rest_seconds: 90, sort_order: 0 },
          { exercise_name: 'Barbell Row', sets: 4, reps_min: 8, reps_max: 10, rest_seconds: 90, sort_order: 1 },
          { exercise_name: 'Seated Cable Row', sets: 3, reps_min: 10, reps_max: 12, rest_seconds: 75, sort_order: 2 },
          { exercise_name: 'Face Pull', sets: 3, reps_min: 12, reps_max: 15, rest_seconds: 60, sort_order: 3 },
          { exercise_name: 'Barbell Curl', sets: 3, reps_min: 8, reps_max: 12, rest_seconds: 60, sort_order: 4 },
          { exercise_name: 'Hammer Curl', sets: 3, reps_min: 10, reps_max: 12, rest_seconds: 60, sort_order: 5 },
        ],
      },
      {
        day_index: 3,
        day_label: 'Thu',
        split_name: 'Rest',
        is_rest: true,
        sort_order: 3,
        exercises: [],
      },
      {
        day_index: 4,
        day_label: 'Fri',
        split_name: 'Legs',
        is_rest: false,
        sort_order: 4,
        exercises: [
          { exercise_name: 'Barbell Squat', sets: 4, reps_min: 8, reps_max: 10, rest_seconds: 120, sort_order: 0 },
          { exercise_name: 'Romanian Deadlift', sets: 3, reps_min: 8, reps_max: 10, rest_seconds: 120, sort_order: 1 },
          { exercise_name: 'Leg Press', sets: 3, reps_min: 10, reps_max: 12, rest_seconds: 90, sort_order: 2 },
          { exercise_name: 'Leg Curl', sets: 3, reps_min: 10, reps_max: 12, rest_seconds: 75, sort_order: 3 },
          { exercise_name: 'Standing Calf Raise', sets: 4, reps_min: 12, reps_max: 15, rest_seconds: 60, sort_order: 4 },
        ],
      },
      {
        day_index: 5,
        day_label: 'Sat',
        split_name: 'Rest',
        is_rest: true,
        sort_order: 5,
        exercises: [],
      },
      {
        day_index: 6,
        day_label: 'Sun',
        split_name: 'Rest',
        is_rest: true,
        sort_order: 6,
        exercises: [],
      },
    ],
  },
];

module.exports = {
  INGREDIENTS,
  MEALS,
  WORKOUT_PLANS,
};
