import type { WorkoutTrack } from '../../types/workout';
import { day, ex } from './builder';

export const MASS_GAIN_TRACK: WorkoutTrack = {
  id: 'mass_gain',
  slug: 'mass_gain',
  title: 'Lean Mass Gain',
  description: '8-day split: upper / lower + shoulders with 4×8–12 volume and drop sets.',
  durationWeeks: 1,
  days: [
    day(1, 1, 'Day 1 — Upper', [
      ex('Dumbbell Press', 4, '8-10'),
      ex('Pull-ups', 4, '10-12'),
      ex('Pec Deck', 4, '12'),
      ex('Barbell Row', 4, '10-12'),
      ex('Hammer Curls', 4, '12-15'),
      ex('Overhead Rope Extension (Low Pulley)', 4, '12'),
    ]),
    day(1, 2, 'Day 2 — Legs + Shoulders', [
      ex('Smith Machine Squat', 4, '12'),
      ex('Leg Extensions', 4, '12'),
      ex('Leg Curls', 4, '12'),
      ex('Hyperextension', 4, '20'),
      ex('Leg Press', 4, '12'),
      ex('Dumbbell Press', 4, '12'),
      ex('Cable Flyes (Low Pulley)', 4, '12'),
      ex('Rear Delt Flyes (Seated)', 4, '12'),
      ex('Barbell Upright Row', 4, '12'),
    ]),
    day(1, 3, 'Day 3 — Upper', [
      ex('Incline Smith Machine Press', 4, '12'),
      ex('Seated Cable Row', 4, '12'),
      ex('Handle Push-ups', 4, '15-20'),
      ex('Lat Pulldown', 4, '12'),
      ex('EZ-Bar Curl', 4, '12'),
      ex('Close-Grip Bench Press', 4, '12-15'),
    ]),
    day(1, 4, 'Day 4 — Lower + Shoulders', [
      ex('Leg Press', 4, '12'),
      ex('Walking Lunges', 4, '10/leg'),
      ex('Standing Calf Raise (Smith)', 4, '12'),
      ex('Lateral Raises (Drop Set 70/50/30%)', 4, '10', {
        dropSetPercents: [70, 50, 30],
      }),
      ex('Face Pull', 4, '12'),
    ]),
    day(1, 5, 'Day 5 — Upper', [
      ex('Medicine Ball Push-ups', 4, '15-20'),
      ex('One-Arm Dumbbell Row', 4, '12/side'),
      ex('Cable Crossover', 4, '12-15'),
      ex('Hammer Strength Row', 4, '12'),
      ex('Rope Biceps Curl', 4, '12'),
      ex('Triceps Extension (High Pulley)', 4, '12'),
    ]),
    day(1, 6, 'Day 6 — Lower + Shoulders', [
      ex('Platform Lunges (Single Leg)', 4, '12/leg'),
      ex('Leg Extensions', 4, '12'),
      ex('Leg Curls', 4, '12'),
      ex('Deep Goblet Squats', 4, '12'),
      ex('Standing Dumbbell Calf Raise', 4, '12'),
      ex('Cable Upright Row', 4, '12'),
      ex('Incline Rear Delt Flyes (45° Bench)', 4, '12'),
    ]),
    day(1, 7, 'Day 7 — Upper', [
      ex('Barbell Bench Press (70% 1RM)', 4, '12', { intensityPercentage: 70 }),
      ex('Seated Lat Pulldown', 4, '12'),
      ex('Pec Deck', 4, '15-20'),
      ex('Bar Row to Chest', 4, '12'),
      ex('Reverse Pec Deck Row (Back)', 4, '12'),
      ex('Hammer Curls', 4, '12'),
      ex('Incline Dumbbell Triceps Extension (30°)', 4, '12'),
    ]),
    day(1, 8, 'Day 8 — Lower + Shoulders', [
      ex('Smith Machine Lunges', 4, '12/leg'),
      ex('Bulgarian Split Squats', 4, '10/leg'),
      ex('Leg Extensions', 4, '12'),
      ex('Leg Curls', 4, '12'),
      ex('Smith Machine Calf Raise', 4, '12'),
      ex('Dumbbell Press', 4, '12'),
      ex('Cable Flyes (Low Pulley)', 4, '12-15'),
      ex('Face Pull', 4, '12'),
    ]),
  ],
};
